### ISSUE TITLE
Automated build failing on Docker Hub/ Docker Cloud

### ISSUE THREAD

**Issue by 0o-de-lally** [markoshust/docker-meteor#1]
I see you're working on this repo at the moment, and it might be unstable for that reason.. FYI I'm getting a failure on Docker Hub / Cloud: 

ERROR: Build failed: The command '/bin/sh -c cd /opt/app/programs/server   && ([ -f package.json ] || npm init -f)   && npm i' returned a non-zero code: 2

Thanks for maintaining this, it looks like a promising alternative to meteorD.

**Comment by markshust** [comment]
All fixed (I think some time ago ;)
