### ISSUE TITLE
Question: Settings json

### ISSUE THREAD

**Issue by xanatas** [markoshust/docker-meteor#3]
Question: How does your settings.json look like
with the cat command i get "\"public\":" is not a valid repository/tag because the " seem not be parsed correctly or something from my settings .json

{
  "public": {
    "userdata":"follow"
  }
}

**Comment by xanatas** [comment]
Got. spaces issue. remove all whitespace.

**Comment by markshust** [comment]
Cool. Were you referencing this line?

```
PRODUCTION_METEOR_SETTINGS=$(cat ./.config/settings-production.json)
```

I believe that should work, with the settings-production.json file containing whitespace. It should.

**Comment by xanatas** [comment]
yes this line. had to make a one-liner out of the json without spaces.

i still have difficulties running the images. its exiting right away... on my machine 

with node main.js it runs 😢

**Comment by markshust** [comment]
Hmm, I'll double check this config. It should run with settings.json having spaces & newlines. If it doesn't, this is indeed a bug.

I'll need a more verbose explanation of the probs you are having running the image. Are you able to build the new docker image? If so, what errors are you having running the image?

**Comment by xanatas** [comment]
the settings bug is still there the other things now work. it was a compiling problem with npm.

**Comment by markshust** [comment]
@xanatas can you setup a test github repo with this? then we can reopen this ticket. I'm unable to duplicate, works fine for me
